exclude = ["**/Cargo.lock", "**/target/**/*"]

[formatting]
allowed_blank_lines = 1
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = [
  "workspace.dependencies",
  "dependencies",
  "dev-dependencies",
  "features",
]

[rule.formatting]
reorder_keys = true
