# spell-checker: ignore dtolnay taiki Swatinem binstall taplo rustup

name: Deploy cargo-gungraun
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish cargo-gungraun
        run: cargo publish -p cargo-gungraun --token ${{ secrets.CRATES_GITHUB_TOKEN }}
